image: "python:3.6"

services:
  - postgres

before_script:
  - "psql -c 'create database events;' -U postgres"
  - "psql -c 'create database events-test;' -U postgres"

stages:
  - test

test:
  script:
  # this configures flask application to use attached postgres database that is run on `postgres` host
  - export DATABASE_URL=postgres://postgres:@postgres:5432/events
  - export TEST_DATABASE_URL=postgres://postgres:@postgres:5432/events-test
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install -r requirements.txt
  - nosetests -v --with-coverage --cover-package=app
